const fs = require('fs');
fs.writeFileSync('server/routes/report.js', [
'const express = require(\'express\');',
'const router = express.Router();',
'const { requireAuth } = require(\'../middleware/auth\');',
'const { Pool } = require(\'pg\');',
'const PDFDocument = require(\'pdfkit\');',
'const nodemailer = require(\'nodemailer\');',
'const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });',
'function getTransporter() { return nodemailer.createTransport({ host: process.env.SMTP_HOST, port: parseInt(process.env.SMTP_PORT||\'587\'), secure: false, auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } }); }',
'async function buildPDF(user, notes) {',
'  return new Promise((resolve, reject) => {',
'    const doc = new PDFDocument({ margin: 50, size: \'LETTER\' });',
'    const chunks = []; doc.on(\'data\', c => chunks.push(c)); doc.on(\'end\', () => resolve(Buffer.concat(chunks))); doc.on(\'error\', reject);',
'    const pw = doc.page.width - 100;',
'    const today = new Date().toLocaleDateString(\'en-US\', { weekday: \'long\', year: \'numeric\', month: \'long\', day: \'numeric\' });',
'    doc.rect(0,0,doc.page.width,90).fill(\'#1B2E4B\');',
'    doc.fontSize(26).fillColor(\'#E8651A\').font(\'Helvetica-Bold\').text(\'BLDR\',50,20);',
'    doc.fontSize(10).fillColor(\'white\').font(\'Helvetica\').text(\'Daily Field Report\',50,50);',
'    doc.fontSize(10).fillColor(\'white\').text(today,50,65);',
'    doc.fontSize(10).fillColor(\'white\').font(\'Helvetica-Bold\').text(user.name,0,30,{align:\'right\',width:doc.page.width-50});',
'    doc.fontSize(10).fillColor(\'white\').font(\'Helvetica\').text(user.project,0,46,{align:\'right\',width:doc.page.width-50});',
'    const tc={}; notes.forEach(n=>{tc[n.type]=(tc[n.type]||0)+1;});',
'    const sy=110,bw=pw/4,colors={issue:\'#DC2626\',progress:\'#16A34A\',rfi:\'#1B2E4B\',other:\'#4B5563\'},labels={issue:\'Issues\',progress:\'Progress\',rfi:\'RFIs\',other:\'Other\'};',
'    [\'issue\',\'progress\',\'rfi\',\'other\'].forEach((type,i)=>{',
'      const x=50+i*bw,count=tc[type]||0;',
'      doc.rect(x,sy,bw-4,54).fill(count>0?colors[type]:\'#F5F6F8\');',
'      doc.fontSize(24).fillColor(count>0?\'white\':\'#4B5563\').font(\'Helvetica-Bold\').text(String(count),x,sy+6,{width:bw-4,align:\'center\'});',
'      doc.fontSize(9).fillColor(count>0?\'white\':\'#4B5563\').font(\'Helvetica\').text(labels[type],x,sy+36,{width:bw-4,align:\'center\'});',
'    });',
'    let y=sy+74;',
'    for(const type of [\'issue\',\'progress\',\'rfi\']){',
'      const tn=notes.filter(n=>n.type===type); if(!tn.length) continue;',
'      if(y>doc.page.height-150){doc.addPage();y=50;}',
'      const sl={issue:\'ISSUES\',progress:\'PROGRESS NOTES\',rfi:\'RFIs\'};',
'      doc.rect(50,y,pw,22).fill(\'#1B2E4B\');',
'      doc.fontSize(10).fillColor(\'white\').font(\'Helvetica-Bold\').text(sl[type],58,y+6);',
'      y+=30;',
'      for(const note of tn){',
'        if(y>doc.page.height-200){doc.addPage();y=50;}',
'        const s=note.structured||{};',
'        const time=new Date(note.createdAt||note.created_at).toLocaleTimeString(\'en-US\',{hour:\'2-digit\',minute:\'2-digit\'});',
'        doc.rect(50,y,pw,2).fill(\'#F5F6F8\');y+=6;',
'        doc.fontSize(8).fillColor(\'#4B5563\').font(\'Helvetica\').text(time,50,y);',
'        if(s.area) d