const PizZip = require('pizzip');
const Docxtemplater = require('docxtemplater');
const fs = require('fs');
const path = require('path');

// We'll use officegen to create proper .docx files with placeholders
// Install it first
const { execSync } = require('child_process');

try {
  require('officegen');
} catch(e) {
  console.log('Installing officegen...');
  execSync('npm install officegen', { stdio: 'inherit' });
}

const officegen = require('officegen');

function buildDailyReport() {
  const docx = officegen('docx');
  
  const addLine = (text, bold = false, size = 20) => {
    const p = docx.createP();
    p.addText(text, { bold, font_size: size });
    return p;
  };

  const addBlank = () => docx.createP();

  // Header
  addLine('CPJ CONSTRUCTION DAILY REPORT', true, 24);
  addBlank();

  // Project Info Table row 1
  addLine('Project Name: {{project_name}}    Project No: {{project_number}}    Date: {{date}}    Day: {{day_number}}', false);
  addLine('Superintendent: {{superintendent_name}}    PM Email: {{pm_email}}    Weather Report No: {{report_number}}', false);
  addBlank();

  // Weather
  addLine('WEATHER', true);
  addLine('AM Temp: {{weather_am_temp}}    PM Temp: {{weather_pm_temp}}    Condition: {{weather_condition}}', false);
  addLine('Rain Start: {{rain_start}}    Rain End: {{rain_end}}    Delay Hours: {{weather_delay_hours}}', false);
  addBlank();

  // Site Conditions
  addLine('SITE CONDITIONS', true);
  addLine('{{site_conditions}}', false);
  addBlank();

  // Logistical Changes
  addLine('LOGISTICAL CHANGES / GENERAL NOTES', true);
  addLine('{{general_notes}}', false);
  addBlank();

  // Work Accomplished
  addLine('WORK ACCOMPLISHED TODAY', true);
  addLine('{{work_accomplished}}', false);
  addBlank();

  // Manpower
  addLine('TRADE CONTRACTOR MANPOWER', true);
  addLine('{{manpower_summary}}', false);
  addBlank();

  // Issues
  addLine('ISSUES / SAFETY', true);
  addLine('{{issues_summary}}', false);
  addBlank();

  // RFIs
  addLine('RFIs REFERENCED TODAY', true);
  addLine('{{rfis_summary}}', false);
  addBlank();

  // Equipment
  addLine('EQUIPMENT ON SITE', true);
  addLine('{{equipment_summary}}', false);
  addBlank();

  // Deliveries
  addLine('DELIVERIES', true);
  addLine('{{deliveries_summary}}', false);
  addBlank();

  // Visitors
  addLine('VISITORS', true);
  addLine('{{visitors_summary}}', false);
  addBlank();

  // Footer
  addLine('Report generated by ARI — {{generated_at}}', false, 16);

  return docx;
}

function buildRFI() {
  const docx = officegen('docx');
  const addLine = (text, bold = false) => { const p = docx.createP(); p.addText(text, { bold }); return p; };
  const addBlank = () => docx.createP();

  addLine('CPJ CONSTRUCTION — REQUEST FOR INFORMATION (RFI)', true, 24);
  addBlank();
  addLine('Project Name: {{project_name}}    Project No: {{project_number}}', false);
  addLine('RFI Number: {{rfi_number}}    Date Submitted: {{date_submitted}}    Date Required: {{date_required}}', false);
  addLine('Priority: {{priority}}    Type: {{rfi_type}}', false);
  addLine('Submitted By: {{submitted_by}}    To: {{addressed_to}}', false);
  addBlank();
  addLine('REQUEST', true);
  addLine('{{request_text}}', false);
  addBlank();
  addLine('PROPOSED SOLUTION', true);
  addLine('{{proposed_solution}}', false);
  addBlank();
  addLine('RESPONSE', true);
  addLine('{{response_text}}', false);
  addBlank();
  addLine('Change Order Required: {{change_order_required}}    Cost Impact: {{cost_impact}}', false);

  return docx;
}

function buildIssueTracker() {
  const docx = officegen('docx');
  const addLine = (text, bold = false) => { const p = docx.createP(); p.addText(text, { bold }); return p; };
  const addBlank = () => docx.createP();

  addLine('CPJ CONSTRUCTION — ISSUE TRACKER', true, 24);
  addBlank();
  addLine('Project: {{project_name}}    Project No: {{project_number}}    Generated: {{date}}', false);
  addBlank();
  addLine('DATE | ISSUE | DESCRIPTION | PRIORITY | COMMENTS', true);
  addLine('{{issues_table}}', false);

  return docx;
}

const templatesDir = path.join(__dirname, '..', 'templates');

['BLDR_Daily_Construction_Report.docx', 'BLDR_RFI_Template.docx', 'BLDR_Issue_Tracker.docx'].forEach(f => {
  const backup = path.join(templatesDir, f.replace('.docx', '_OLD.docx'));
  if (fs.existsSync(path.join(templatesDir, f))) {
    fs.copyFileSync(path.join(templatesDir, f), backup);
    console.log('Backed up:', f);
  }
});

const dailyOut = fs.createWriteStream(path.join(templatesDir, 'BLDR_Daily_Construction_Report.docx'));
const rfiOut = fs.createWriteStream(path.join(templatesDir, 'BLDR_RFI_Template.docx'));
const issueOut = fs.createWriteStream(path.join(templatesDir, 'BLDR_Issue_Tracker.docx'));

buildDailyReport().generate('nodebuffer', (err, buf) => {
  if (err) { console.error('Daily report error:', err); return; }
  fs.writeFileSync(path.join(templatesDir, 'BLDR_Daily_Construction_Report.docx'), buf);
  console.log('✅ Daily report template rebuilt');
});

buildRFI().generate('nodebuffer', (err, buf) => {
  if (err) { console.error('RFI error:', err); return; }
  fs.writeFileSync(path.join(templatesDir, 'BLDR_RFI_Template.docx'), buf);
  console.log('✅ RFI template rebuilt');
});

buildIssueTracker().generate('nodebuffer', (err, buf) => {
  if (err) { console.error('Issue tracker error:', err); return; }
  fs.writeFileSync(path.join(templatesDir, 'BLDR_Issue_Tracker.docx'), buf);
  console.log('✅ Issue tracker template rebuilt');
});
