const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType, HeadingLevel } = require('docx');
const fs = require('fs');
const path = require('path');

const templatesDir = path.join(__dirname, '..', 'templates');

function t(text) {
  return new Paragraph({ children: [new TextRun(text)] });
}
function h(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, bold: true })] });
}
function blank() {
  return new Paragraph({ children: [new TextRun('')] });
}

// DAILY CONSTRUCTION REPORT
const dailyDoc = new Document({ sections: [{ children: [
  new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: 'CPJ CONSTRUCTION — DAILY CONSTRUCTION REPORT', bold: true })] }),
  blank(),
  t('Project Name: {{project_name}}'),
  t('Project No: {{project_number}}'),
  t('Date: {{date}}    Day of Week: {{day_of_week}}    Report No: {{report_number}}'),
  t('Superintendent: {{superintendent_name}}'),
  t('PM Email: {{pm_email}}'),
  blank(),
  h('WEATHER'),
  t('AM Temp: {{weather_am_temp}}°F    PM Temp: {{weather_pm_temp}}°F'),
  t('Condition: {{weather_condition}}'),
  t('Rain/Weather Delay: {{weather_delay}}    Delay Hours: {{weather_delay_hours}}'),
  blank(),
  h('SITE CONDITIONS'),
  t('{{site_conditions}}'),
  blank(),
  h('LOGISTICAL CHANGES / GENERAL NOTES'),
  t('{{general_notes}}'),
  blank(),
  h('WORK ACCOMPLISHED TODAY'),
  t('{{work_accomplished}}'),
  blank(),
  h('TRADE CONTRACTOR MANPOWER'),
  t('{{manpower_summary}}'),
  blank(),
  h('2ND TIER CONTRACTORS'),
  t('{{second_tier_summary}}'),
  blank(),
  h('TEMPORARY LABORERS'),
  t('{{temp_laborers}}'),
  blank(),
  h('VISITORS'),
  t('{{visitors_summary}}'),
  blank(),
  h('EQUIPMENT ON SITE'),
  t('{{equipment_summary}}'),
  blank(),
  h('DELIVERIES'),
  t('{{deliveries_summary}}'),
  blank(),
  h('SAFETY ISSUES'),
  t('{{safety_issues}}'),
  blank(),
  h('RFIs'),
  t('{{rfis_summary}}'),
  blank(),
  h('T&M WORK'),
  t('{{tm_work}}'),
  blank(),
  h('PROGRESS PHOTOS'),
  t('{{progress_photos}}'),
  blank(),
  t('Report generated by BLDR — {{generated_at}}'),
]}]});

// RFI TEMPLATE
const rfiDoc = new Document({ sections: [{ children: [
  new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: 'CPJ CONSTRUCTION — REQUEST FOR INFORMATION (RFI)', bold: true })] }),
  blank(),
  t('Project Name: {{project_name}}    Project No: {{project_number}}'),
  t('RFI Number: {{rfi_number}}    Date Submitted: {{date_submitted}}'),
  t('Date Required: {{date_required}}    Priority: {{priority}}'),
  t('Type: {{rfi_type}}'),
  t('Submitted By: {{submitted_by}}    Addressed To: {{addressed_to}}'),
  blank(),
  h('REQUEST'),
  t('{{request_text}}'),
  blank(),
  h('PROPOSED SOLUTION'),
  t('{{proposed_solution}}'),
  blank(),
  h('RESPONSE'),
  t('{{response_text}}'),
  blank(),
  t('Change Order Required: {{change_order_required}}'),
  t('Cost Impact: {{cost_impact}}'),
]}]});

// ISSUE TRACKER
const issueDoc = new Document({ sections: [{ children: [
  new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: 'CPJ CONSTRUCTION — ISSUE TRACKER', bold: true })] }),
  blank(),
  t('Project: {{project_name}}    Project No: {{project_number}}'),
  t('Generated: {{date}}    Superintendent: {{superintendent_name}}'),
  blank(),
  h('ISSUES LOG'),
  t('{{issues_table}}'),
]}]});

async function build() {
  const dailyBuf = await Packer.toBuffer(dailyDoc);
  fs.writeFileSync(path.join(templatesDir, 'BLDR_Daily_Construction_Report.docx'), dailyBuf);
  console.log('✅ Daily report template rebuilt');

  const rfiBuf = await Packer.toBuffer(rfiDoc);
  fs.writeFileSync(path.join(templatesDir, 'BLDR_RFI_Template.docx'), rfiBuf);
  console.log('✅ RFI template rebuilt');

  const issueBuf = await Packer.toBuffer(issueDoc);
  fs.writeFileSync(path.join(templatesDir, 'BLDR_Issue_Tracker.docx'), issueBuf);
  console.log('✅ Issue tracker template rebuilt');
}

build().catch(console.error);
